CREATE DATABASE IF NOT EXISTS moderncarwebsite CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE moderncarwebsite;
CREATE TABLE brands (id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL UNIQUE,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE cars (id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(160) NOT NULL,brand_id INT NOT NULL,year INT NOT NULL,price INT NOT NULL,color VARCHAR(80) NOT NULL,color_hex VARCHAR(9) NOT NULL DEFAULT '#8a8d91',description TEXT NOT NULL,thumbnail TEXT NOT NULL,images JSON NOT NULL,sketchfab_url TEXT NULL,model_path TEXT NULL,featured TINYINT(1) NOT NULL DEFAULT 0,specs JSON NOT NULL,features JSON NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,CONSTRAINT fk_car_brand FOREIGN KEY(brand_id) REFERENCES brands(id));
CREATE TABLE admin_users (id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL,email VARCHAR(190) NOT NULL UNIQUE,password_hash VARCHAR(255) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
INSERT INTO admin_users(name,email,password_hash) VALUES ('Showroom Admin','admin@showroom.com','$2y$12$bQC9fjk8Q2rShBHloKb1hujVPMkxsyCk8H3u1zk9Lp6UXX.nGJ8GG');
INSERT INTO brands(name) VALUES ('Porsche'),('Ferrari'),('Mercedes-AMG');
INSERT INTO cars(name,brand_id,year,price,color,color_hex,description,thumbnail,images,featured,specs,features) VALUES
('911 GT3 RS',1,2024,241300,'GT Silver','#b8bcc2','A road-legal racing machine shaped by motorsport.','https://images.pexels.com/photos/112460/pexels-photo-112460.jpeg',JSON_ARRAY('https://images.pexels.com/photos/112460/pexels-photo-112460.jpeg','https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg'),1,JSON_OBJECT('horsepower',518,'topSpeed',184,'acceleration',3.0,'engine','4.0L Flat-Six','transmission','7-Speed PDK','drivetrain','RWD','seats',2),JSON_ARRAY('Rear-wheel steering','Carbon ceramic brakes','Active aerodynamics')),
('296 GTB',2,2024,342205,'Rosso Corsa','#b51f2e','A compact mid-engine hybrid supercar with extraordinary response.','https://images.pexels.com/photos/337909/pexels-photo-337909.jpeg',JSON_ARRAY('https://images.pexels.com/photos/337909/pexels-photo-337909.jpeg'),1,JSON_OBJECT('horsepower',819,'topSpeed',205,'acceleration',2.9,'engine','3.0L V6 Hybrid','transmission','8-Speed DCT','drivetrain','RWD','seats',2),JSON_ARRAY('Hybrid boost','Carbon cockpit','Adaptive dynamics')),
('AMG GT 63',3,2024,177900,'Obsidian Black','#151515','A grand touring coupe combining handcrafted power with everyday usability.','https://images.pexels.com/photos/120049/pexels-photo-120049.jpeg',JSON_ARRAY('https://images.pexels.com/photos/120049/pexels-photo-120049.jpeg'),1,JSON_OBJECT('horsepower',577,'topSpeed',196,'acceleration',3.1,'engine','4.0L Twin-Turbo V8','transmission','9-Speed MCT','drivetrain','AWD','seats',4),JSON_ARRAY('AMG Performance 4MATIC+','Rear axle steering','Burmester audio'));
